version: "2"

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true

linters:
  default: all
  disable:
    - bodyclose
    - cyclop
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - lll
    - mnd
    - nlreturn
    - paralleltest
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl # deprecated

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/instana/testify
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    funlen:
      lines: -1
      statements: 50
    goconst:
      min-len: 5
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - sloppyReassign
        - rangeValCopy
        - octalLiteral
        - hugeParam
        - paramTypeCombine # already handled by gofumpt.extra-rules
      enabled-tags:
        - diagnostic
        - style
        - performance
    gocyclo:
      min-complexity: 15
    godox:
      keywords:
        - FIXME
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    perfsprint:
      err-error: true
      errorf: true
      sprintf1: true
      strconcat: false

  exclusions:
    warn-unused: true
    rules:
      - linters:
          - funlen
        path: .*_test.go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
